from rdkit import Chem
from rdkit.Chem import QED
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent  # src/train.py -> src/ -> project root

from src.split import get_scaffold

def compute_validity(smiles_list):
    """
    This function takes in a list of SMILES strings, and identifies whether each string is a valid molecule.

    Parameters:
        smiles_list: List of SMILES strings

    Returns:
        valid_smiles, invalid_count
        valid_smiles: List of all valid smiles in smiles_list, in canonical representation.
        invalid_count: Count of smiles strings in smiles_list that are not valid molecules. 
    """
    invalid_count = 0
    valid_smiles = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            invalid_count += 1
        else:
            # Getting canonical_smiles this way guarantees that all equivalent molecules are expressed in only one way
            canonical_smiles = Chem.MolToSmiles(mol)
            valid_smiles.append(canonical_smiles)
    return valid_smiles, invalid_count


def compute_uniqueness(smiles_list):
    """
    This function takes in a list of SMILES strings and calculates the percentage of unique strings in the list.

    Parameters:
        smiles_list: List of SMILES strings

    Returns:
        Percentage of unique strings in smiles_list
    """
    if len(smiles_list) == 0:
        return 0
    return len(set(smiles_list)) / len(smiles_list)


def compute_novelty(canonical_training_smiles, valid_generated_smiles):
    """
    This functions takes in a set of generated SMILES strings and determines which strings are novel (not in the training set).
    
    Parameters:
        canonical_training_smiles: Set of SMILES strings used in training, in canonical representation
        valid_generated_smiles: List of valid SMILES strings generated by model

    Returns:
        novel, not_novel, novelty_rate
        novel: List of novel (not in training set) generated molecules
        not_novel: List of non-novel (in training set) generated molecules
        novelty_rate: Percentage of generated molecules that are novel
    """
    if len(valid_generated_smiles) == 0:
        return [], [], 0.0

    novel = []
    not_novel = []
    # Only get unique smiles
    valid_generated_smiles = set(valid_generated_smiles)
    for smiles in valid_generated_smiles:
        if smiles in canonical_training_smiles:
            not_novel.append(smiles)
        else:
            novel.append(smiles)

    novelty_rate = len(novel) / len(valid_generated_smiles)
    return novel, not_novel, novelty_rate


def compute_qed_scores(smiles_list):
    """
    This function computes the QED (Quantitative Estimate of Drug-likeliness) score for a list of inputted SMILES strings.

    Parameters:
        smiles_list: List of SMILES strings

    Returns:
        scores: List of QED scores for the corresponding inputted SMILES strings
    """
    scores = []
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        scores.append(QED.qed(mol))
    return scores


def scaffold_breakdown(smiles_list, train_scaffolds, holdout_scaffolds):
    """
    This function breakdowns a list of SMILES strings into three groups:
        train_scaffold_matches: SMILES strings with a scaffold in the training set
        holdout_scaffold_matches: SMILES strings with a scaffold in the holdout set
        outside_dataset_scaffolds: SMILES strings with a scaffold in neither the training or holdout set

    Parameters:
        smiles_list: List of SMILES strings
        train_scaffolds: List of scaffolds in the training set
        holdout_scaffolds: List of scaffolds in the holdout set

    Returns:
        Dictionary with 3 lists corresponding to each group: train_scaffold_matches, holdout_scaffold_matches, and outside_dataset_scaffolds
    """

    train_scaffold_matches = []
    holdout_scaffold_matches = []
    outside_dataset_scaffolds = []
    for smiles in smiles_list:
        scaffold = get_scaffold(smiles)
        if scaffold in train_scaffolds:
            train_scaffold_matches.append(smiles)
        elif scaffold in holdout_scaffolds:
            holdout_scaffold_matches.append(smiles)
        else:
            outside_dataset_scaffolds.append(smiles)

    return {"train_scaffold_matches": train_scaffold_matches, "holdout_scaffold_matches": holdout_scaffold_matches, "outside_dataset_scaffolds": outside_dataset_scaffolds}

def compute_scaffold_holdout_rate(scaffold_breakdown):
    """
    Given a scaffold breakdown dictionary, compute the scaffold holdout rate (the % of SMILES strings with a scaffold in the holdout set)

    Parameters:
        scaffold_breakdown: Dictionary with 3 lists corresponding to each group: train_scaffold_matches, holdout_scaffold_matches, and outside_dataset_scaffold

    Returns:
        Percentage of SMILES strings with a scaffold in the holdout set
    """

    total = len(scaffold_breakdown['train_scaffold_matches']) + len(scaffold_breakdown['holdout_scaffold_matches']) + len(scaffold_breakdown['outside_dataset_scaffolds'])
    if total == 0:
        return 0.0
    return len(scaffold_breakdown['holdout_scaffold_matches']) / total

def compute_scaffold_novelty_rate(scaffold_breakdown):
    """
    Given a scaffold breakdown dictionary, compute the scaffold novelty rate (the % of SMILES strings with a scaffold not in the training set)

    Parameters:
        scaffold_breakdown: Dictionary with 3 lists corresponding to each group: train_scaffold_matches, holdout_scaffold_matches, and outside_dataset_scaffold

    Returns:
        Percentage of SMILES strings with a scaffold not in the training set
    """

    total = len(scaffold_breakdown['train_scaffold_matches']) + len(scaffold_breakdown['holdout_scaffold_matches']) + len(scaffold_breakdown['outside_dataset_scaffolds'])
    if total == 0:
        return 0.0
    return (len(scaffold_breakdown['holdout_scaffold_matches']) + len(scaffold_breakdown['outside_dataset_scaffolds'])) / total